name = "wag"
version = "0.1.0"
target = "javascript"

description = "Send and receive messages using a cloud-hosted version of the WhatsApp Business Platform."
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "wag" }
links = []

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 2.3.0 and < 4.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
oas = ">= 6.0.0 and < 8.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_fetch = ">= 1.3.0 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
